version: '3.7'
services:
  auth:
    container_name: auth-container
    build:
      context: auth
      dockerfile: Dockerfile
    environment:
      - APP_VERSION=1.0.0
      - API_DEFAULT_PREFIX="/api/v1"
      - API_DEFAULT_PORT=3031
      - SWAGGER_TITLE="DB service"
      - SWAGGER_DESCRIPTION="DB service Swagger UI"
      - SWAGGER_PREFIX="/docs"
      - USER_SERVICE_URL=http://localhost:3033
    ports:
      - 3031:3031
  db:
    container_name: db-container
    build:
      context: db
      dockerfile: Dockerfile
    environment:
      - APP_VERSION=1.0.0
      - API_DEFAULT_PREFIX="/api/v1"
      - API_DEFAULT_PORT=3032
      - SWAGGER_TITLE="DB service"
      - SWAGGER_DESCRIPTION="DB service Swagger UI"
      - SWAGGER_PREFIX="/docs"
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=users
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=zRpvW3VBgwCMMX5c
      - POSTGRES_SYNC=true
      - POSTGRES_RUN_MIGRATION=true
    ports:
      - 3032:3032
  user:
    container_name: user-container
    build:
      context: user
      dockerfile: Dockerfile
    environment:
      - APP_VERSION=1.0.0
      - API_DEFAULT_PREFIX="/api/v1"
      - API_DEFAULT_PORT=3033
      - SWAGGER_TITLE="USER service"
      - SWAGGER_DESCRIPTION="USER service Swagger UI"
      - SWAGGER_PREFIX="/docs"
      - DB_SERVICE_URL=http://localhost:3032
    ports:
      - 3033:3033
  postgres:
    image: kartoza/postgis:12.0
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASS=zRpvW3VBgwCMMX5c
      - POSTGRES_DBNAME=users
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,btree_gist
